export const HTTP_404_ERROR = 'HTTP_404_ERROR';
export const HTTP_500_ERROR = 'HTTP_500_ERROR';

export const LOCATION_FETCH_REQUEST = "LOCATION_FETCH_REQUEST";
export const LOCATION_FETCH_REQUEST_SUCCESS = "LOCATION_FETCH_REQUEST_SUCCESS";
export const LOCATION_FETCH_REQUEST_FAILURE = "LOCATION_FETCH_REQUEST_FAILURE";

export const HOTEL_FETCH_REQUEST = "HOTEL_FETCH_REQUEST";
export const HOTEL_FETCH_REQUEST_SUCCESS = "HOTEL_FETCH_REQUEST_SUCCESS";
export const HOTEL_FETCH_REQUEST_FAILURE = "HOTEL_FETCH_REQUEST_FAILURE";

export const PACKAGES_FETCH_REQUEST = "PACKAGES_FETCH_REQUEST";
export const PACKAGES_FETCH_REQUEST_SUCCESS = "PACKAGES_FETCH_REQUEST_SUCCESS";
export const PACKAGES_FETCH_REQUEST_FAILURE = "PACKAGES_FETCH_REQUEST_FAILURE";

export const TREK_FETCH_REQUEST = "TREK_FETCH_REQUEST";
export const TREK_FETCH_REQUEST_SUCCESS = "TREK_FETCH_REQUEST_SUCCESS";
export const TREK_FETCH_REQUEST_FAILURE = "TREK_FETCH_REQUEST_FAILURE";

export const LOCATION_CLEAN_REQUEST = 'LOCATION_CLEAN_REQUEST';
export const HOTEL_CLEAN_REQUEST = 'HOTEL_CLEAN_REQUEST';
export const TREK_CLEAN_REQUEST = 'TREK_CLEAN_REQUEST';
export const PACKAGES_CLEAN_REQUEST = 'PACKAGES_CLEAN_REQUEST';
