export const HTTP_404_ERROR = 'HTTP_404_ERROR';
export const HTTP_500_ERROR = 'HTTP_500_ERROR';

export const LOCATION_FETCH_REQUEST = "LOCATION_FETCH_REQUEST";
export const LOCATION_FETCH_REQUEST_SUCCESS = "LOCATION_FETCH_REQUEST_SUCCESS";
export const LOCATION_FETCH_REQUEST_FAILURE = "LOCATION_FETCH_REQUEST_FAILURE";

export const LOCATION_CLEAN_REQUEST = 'LOCATION_CLEAN_REQUEST'
